### ISSUE TITLE
Implement additional PCV dose for Preterms

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#32]
- [x] Implement PCV4 for children that are born prematurely as described [[here](https://docs.google.com/document/d/13OyTj_ofX89WX5YGZYp2Sf2P-hM6s-V1zGX9Mwwxi1M/edit)] using calculations 
 on #30. 
- [x] When a child has been born prematurely, the PCV doses will be 4 on their immunization schedule, this will also reflect on their historical data. 
- [ ] If the mother GA (ga_at_birth) or child's birth weight (birthweight) is edited, the new configuration should be used based on the logic updated.

**Comment by cafootitt** [comment]
@AnnieMungai It would be helpful to include a mockup of where the extra dose will be listed on the profile of premature babies. You could take a screenshot of the vaccine card page of the existing app and then annotate it to show where the additional dose would be loaded.

Also, since they can edit both GA at birth and birthweight by re-opening the registration form, we need to cater to a situation whereby the child is tagged as requiring PCV4 dose and then changes to not requiring PCV4 dose.

**Comment by AnnieMungai** [comment]
App ver 0.0.5- debug (24th July 2020).

Looks really good!
